
name: Build

on:
  push:
    branches: [ main ]

jobs:
  job1:
  
    runs-on: ubuntu-latest
    name: job1
    steps:
     - uses: actions/checkout@v3
     - name: Test hello
       run: |
         echo Hello > file.txt
         cat file.txt
