# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Build

on:
  push:
    branches: [ main ]

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python  3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          echo "Iam main"
          echo "Hello Python3.9"
          echo "start_time=$(printf '%(%s)T' -1)" >> $GITHUB_OUTPUT
  test1:
    name: test2
    runs-on: ubuntu-latest
    needs: [test]
    steps:
     - uses: actions/checkout@v3
     - name: Install
       run: ${{ needs.test.start_time }}
